[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
# rustflags = ["-C","link-args=-Tsrc/linker.ld --verbose", "-C","force-frame-pointers=yes"]
rustflags = ["-C","force-frame-pointers=yes"]
